### ISSUE TITLE
Running server and super dev mode in eclipse

### ISSUE THREAD

**Issue by masterdany88** [steinsag/gwt-maven-example#3]
Hey. Thanks for this project. I've struggled to run gwt 2.7 with maven for over one week.
Thanks to You I have starter up and running. It is great.
Unfortunatelly I can run only maven install from eclipse -> project -> Right mouse button -> Run as -> 8 Maven install

I would like to have possibility to run all from eclipse. Is it possible. Can You give me some help for that.
In oryginal gwt app builded with ant I can do that. RMB on project and run super dev mode.

Please help

**Comment by steinsag** [comment]
Unfortunately, I'm not using Eclipse myself and can't really help you. What's always possible easily is to debug Java server code using remote debugging. Everything else will require much more setup and testing. I suggest to use this project and post a specific question what you tried and where it fails on stackoverflow.com.

**Comment by masterdany88** [comment]
What kind of ide do You use? Is it intelij ultimate/ comunity? Is there it works by clicking? Or do You use only maven in console?
