### ISSUE TITLE
Super dev mode debugging

### ISSUE THREAD

**Issue by calinilie** [steinsag/gwt-maven-example#4]
Hi,

Are you able to debug it in inteliJ whilst running super dev mode (which I assume happens when running ```gwt:run``` goal)?

I am only able to debug it in browser, but that has its limitations: http://stackoverflow.com/questions/25105469/how-to-debug-using-superdev-mode. I was wondering if it is possible to achieve that (watching variables and evaluating expression) in inteliJ, as I am considering switching from eclipse.

thanks

**Comment by steinsag** [comment]
I haven't tried it for some time. But yes, debugging in IntelliJ should work with the setup given.
